config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'pages#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :activities do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    member do
      post 'up-vote'
      post 'down-vote'
    end
  end
  resources :trips do
    member do
      post 'like'
    end
    resources :shortlisted_activities, only: [:show, :new, :create]
    member do
      get 'trip_map'
    end
  end
  resources :users do
    member do
      get 'reviews'
      get 'activities'
    end
  end
  resources :shortlisted_activities, only: [:create, :destroy]
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :shortlisted_activities, dependent: :destroy
  has_many :activities, through: :shortlisted_activities
  validates :duration, presence: true
  validates :duration, numericality: true
  validates :trip_name, length: { in: 5..50 }, on: :update
  validates :description, length: { maximum: 500 }
  validates :likes, numericality: true

  def morning_activities
    morning = ShortlistedActivity.where(trip: self).joins(:activity).where(activities: {tod: 'Morning'})
    day_increment(morning)
  end

  def afternoon_activities
    afternoon = ShortlistedActivity.where(trip: self).joins(:activity).where(activities: {tod: 'Afternoon'})
    day_increment(afternoon)
  end

  def evening_activities
    evening = ShortlistedActivity.where(trip: self).joins(:activity).where(activities: {tod: 'Evening'})
    day_increment(evening)
  end

  def sort_activities
    morning_activities
    afternoon_activities
    evening_activities
  end

  def trip_duration
    (1..duration).to_a
  end

  def day_increment(activities)
    activities.each_with_index do |activity, i|
      if i < duration
        activity.day = i + 1
        activity.save
      else
        activity.day = duration
        activity.save
      end
    end
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy, :like, :trip_map]
  skip_before_action :authenticate_user!, only: :create
  def index
    @user_trips = policy_scope(Trip)
  end

  def show
    @trip.sort_activities
    @shortlisted_activities = @trip.shortlisted_activities
    @review = Review.new
    authorize @trip
  end

  def create
    skip_authorization
    if user_signed_in?
      activity_ids = params[:cardIds]
      # get all ids from params
      if activity_ids.nil?
        activity_array = []
      else
        activity_array = activity_ids.split(",").map(&:to_i).uniq
      end
      # convert it from a string to an array
      # iterate over this array

      # for each one of the ids create a shortlisted activity with the id of the trip you just created
      @trip = Trip.new
      @trip.user = current_user
      @trip.likes = 0
      @trip.duration = params[:days].to_i
      @trip.trip_name = "My trip to #{params[:place]}"
      authorize @trip
      @trip.save
      activity_array.each do |activity|
        ShortlistedActivity.create(activity_id: activity, trip: @trip)
      end
      # create a trip
      @trip.trip_name = "My trip to #{@trip.activities.first.city}"
      @trip.save
      redirect_to trips_path
    else
      trips_params = {}
      trips_params[:days] = params[:days]
      trips_params[:cardIds] = params[:cardIds]
      session[:trips_params] = trips_params
      flash[:alert] = 'You need to sign in or sign up before continuing.'
      redirect_to new_user_session_path
    end
  end

  def edit
  end

  def update
    @trip.update(trip_params)
    redirect_to trips_path
    authorize @trip
  end

  def destroy
    authorize @trip
    @trip.destroy
    redirect_to trips_path
  end

  def like
    @trip.likes += 1
    authorize @trip
    @trip.save
  end

  def trip_map
    all_activities = @trip.shortlisted_activities.joins(:activity)
    @activity_array = []
    all_activities.each do |shortlisted|
      @activity_array << Activity.find(shortlisted.activity_id)
    end

    @markers = @activity_array.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { activity: activity })
      }
    end
    authorize @trip
  end

  private

  def set_trip
    @trip = Trip.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:trip_name, :description, :user_id)
  end
end

app/helpers/trips_helper.rb
module TripsHelper
  def check_photo(activity)
    if activity.nil?
      "default_activity.jpg"
    else
      activity
    end
  end

  def tod_icon_picker(activity)
    if activity.activity.tod == "Morning"
      "sunrise.png"
    elsif activity.activity.tod == "Afternoon"
      "sun.png"
    elsif activity.activity.tod == "Evening"
      "sunset.png"
    end
  end

  def tod_activity_picker(activities, day)
    activities = activities.where(day: day)
    morning = activities.find { |activity| activity.activity.tod == "Morning" }
    afternoon = activities.find { |activity| activity.activity.tod == "Afternoon" }
    evening = activities.find { |activity| activity.activity.tod == "Evening" }
    [morning, afternoon, evening]
  end
end

app/views/trips/_info_window.html.erb
<div class="activity-map-card">
  <h5><%= activity.name %></h5>
  <%= cl_image_tag activity.photo, class: "map-image" %>
  <div>
    <p>Day <%= ShortlistedActivity.find_by(activity: activity).day %>: <%= activity.tod %></p>
  </div>

</div>

app/views/trips/index.html.erb
<div class="trip-show-container">
  <div class="trip-title d-flex justify-content-center flex-column my-trip-head">
    <h4 class="my-trip-title"> My Trips </h4>
  </div>
    <% if @user_trips.empty? %>
      <div class="trip-none">
        <p>You have no trips planned<p>
        <p>Let's change that...</p>
        <%= link_to "Plan New Trip", root_path, class: "btn btn-warning" %>
      </div>
    <% end %>
      <% counter = 0 %>
      <% @user_trips.each do |trip| %>
      <% activity = trip.activities.first || Activity.first %>
      <div class="card-trip">
        <div class="card-trip-infos">
          <div class="index-trip-head">
            <h2><%= link_to trip.trip_name, trip_path(trip, selected_day: 1, selected_time: "Morning") %></h2>
            <p><%= trip.duration %> days</p>
          </div>
          <h2 class="card-trip-pricing"><%= trip.likes %> <i class="fas fa-heart"></i> </h2>
          <img src="<%= asset_path check_photo(activity.photo) %>" class="card-trip-user" />
        </div>
      </div>

      <% end %>

</div>

app/views/trips/like.js.erb
function updateLikes() {
  const numLikes = <%= @trip.likes %>;
  const divLikes = document.querySelector(".triplikes");
  divLikes.innerHTML = `${numLikes} <i class="fas fa-heart"></i>`;
  divLikes.setAttribute('disabled', true);
}

updateLikes();

app/views/trips/show.html.erb
<div class="trip-show-container">
    <div class="my-trip-show-head trip-title d-flex justify-content-center flex-column">
        <h3> <%= @trip.trip_name %> </h3>
        <h5><%= @trip.duration %> days</h5>
    </div>

    <div class="trip-show-header">
      <%= link_to user_path(@trip.user) do %>
        <div class="photo-container-small">
          <%= cl_image_tag(@trip.user.photo.url) %>
        </div>
      <% end %>
      <h5> <%= @trip.user.username %> | </h5>
      <h5> <%= @trip.created_at.day %>/<%= @trip.created_at.month %>/<%= @trip.created_at.year %> | </h5>
      <%= link_to trip_map_trip_path(@trip) do %>
        <i class="fas fa-map-marked-alt"></i>
      <% end %>
    </div>

  <% @trip.trip_duration.each do |day| %>
    <% if @shortlisted_activities.where(day: day).first.nil? %>
      <div class="day-container day-container-opacity mt-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path 'trip_photo.jpg' %>)">
        <a data-toggle="collapse" href="#collapseExample<%= day %>" role="button" aria-expanded="false" aria-controls="collapseExample">

          <h4>Day <%= day %></h4>
          <h6>Nothing planned!</h6>
          <% if @trip.user == current_user %>
            <h6>tap to add</h6>
          <% end %>

        </a>
      </div>
    <% else %>
      <% @activity = @shortlisted_activities.where(day: day).first.activity.photo %>
      <div class="day-container mt-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= @activity %>')">
        <a data-toggle="collapse" href="#collapseExample<%= day %>" role="button" aria-expanded="false" aria-controls="collapseExample">
          <h4>Day <%= day %></h4>
          <h6>tap to expand</h6>
        </a>
      </div>
    <% end %>

    <% tod_activity_picker(@shortlisted_activities, day).each_with_index do |activity, i| %>
      <% if !activity&.activity.nil? %>
        <div class="modal modal-review fade" id="rate-<%= activity.activity.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content modal-content-review">
              <div class="modal-header">
                <h5 class="modal-title modal-title-review" id="exampleModalLabel">Rate</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <%= render 'reviews/star_form', activity: activity.activity %>
              </div>
            </div>
          </div>
        </div>
      <% end  %>

      <% if activity.nil? && @trip.user == current_user  %>
        <div class="collapse" id="collapseExample<%= day %>">
          <div class="card-product background-gray">
            <div class="photo-img-container">
              <%= link_to (image_tag "add_photo.png"), new_trip_shortlisted_activity_path(@trip, day: day, index: i) %>
            </div>
            <div class="card-product-infos">
              <h4>No activity picked!</h4>
              <p>Add your own <strong>adventure</strong>!</p>
            </div>
          </div>
        </div>
      <% elsif activity.nil? %>
      <% else %>
        <div class="collapse" id="collapseExample<%= day %>">
          <div class="card-product">
            <%= cl_image_tag activity.activity.photo %>
            <div class="card-product-infos">
              <h4><%= link_to activity.activity.name.truncate(20), trip_shortlisted_activity_path(@trip, activity) %></h4>
                <div class="starrow" id='star-<%= activity.activity.id %>'>
                  <% activity.activity.reviews.where(user: current_user).each do |review| %>
                      <%= render 'reviews/star_row', review: review %>
                  <% end %>

                  <% if activity.activity.reviews.where(user: current_user).empty? %>
                      <p>You haven't rated this activity</p>
                  <% end %>
                </div>


              <div class="icon-container">
                <div class="icon-inner-container d-flex">
                  <% activity.activity.categories.each do |category| %>
                    <div class="icon-name-container">
                      <i class="<%= category.icon %>"></i>
                    </div>
                  <% end %>
                </div>
                <div class="rate-tod-container d-flex">
                  <div class="tod-icon">
                    <%= image_tag(tod_icon_picker(activity)) %>
                  </div>
                  <button type="button" class="btn btn-warning review-btn-small" data-toggle="modal" data-target="#rate-<%= activity.activity.id %>" data-backdrop="false">
                    Rate
                  </button>
                  <div class="delete-activity">
                    <%= link_to "<i class='far fa-trash-alt'></i>".html_safe, shortlisted_activity_path(activity), method: :delete, class: 'btn delete-btn' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>

  <div class="all-container">
    <div class="trip-user-section">

    <% if @trip.user != current_user %>
      <div class="button-row">
        <%= link_to like_trip_path(@trip), method: :post, remote: true do %>
          <div class="trips-likes-container">
            <button class="btn btn-warning triplikes"><%= @trip.likes %> <i class="fas fa-heart"></i></button>
          </div>
        <% end %>
      </div>

    <% end %>
  </div>
  <% if @trip.user == current_user %>
    <div class="deleterow">
      <%= link_to "<i class='far fa-trash-alt'></i>".html_safe, trip_path(@trip), method: :delete, class: 'btn delete-btn' %>
      <p>Delete</p>
    </div>
  <% end %>
</div>

<% content_for :before_js do %>
  <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<% end %>

app/views/trips/trip_map.html.erb
<div class="map-container">
  <div class="link-trip">
    <%= link_to "Back to trip", trip_path(@trip), class: "btn btn-warning" %>
  </div>
  <div
    id="map"
    style="width: 100%;
    height: 400px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>