config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'pages#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :activities do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    member do
      post 'up-vote'
      post 'down-vote'
    end
  end
  resources :trips do
    member do
      post 'like'
    end
    resources :shortlisted_activities, only: [:show, :new, :create]
    member do
      get 'trip_map'
    end
  end
  resources :users do
    member do
      get 'reviews'
      get 'activities'
    end
  end
  resources :shortlisted_activities, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: true
  has_many :trips, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :activities, dependent: :destroy
  mount_uploader :photo, PhotoUploader

  def country_flag
    country = Country[nationality]
    country.emoji_flag
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    trips_params = session[:trips_params]
    super
    session[:trips_params] = trips_params
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def reviews
    @reviews = current_user.reviews
    authorize @reviews
  end

  def activities
    @activities = current_user.activities
    authorize @activities
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:username, :first_name, :second_name, :nationality, :bio, :photo)
  end

end

app/views/users/activities.html.erb
<%= link_to "Back to profile", user_path(current_user), class: "btn btn-warning link-back" %>
<div class="trip-title d-flex justify-content-center flex-column my-activity-head">
  <h3 class="my-trip-title"> My Activities </h3>
</div>
<div class="all-container activity-display">
  <% if current_user.activities.empty? %>
    <div class="trip-none">
      <p>You haven't added any activities<p>
      <p>Share your experiences...</p>
      <%= link_to "Add an activity", new_activity_path, class: "btn btn-warning" %>
    </div>
  <% end %>
  <div class="row">
    <% current_user.activities.each do |activity| %>
      <div class="col-6 padding-activity">
        <div class="activity-card">
          <img src="<%= asset_path check_photo(activity.photo) %>" class="my-show">
          <div class="activity-info">
            <h6 class="activity-card-name"><%= activity.name %></h6>
            <div class="upadate-activity">
              <%= link_to "<i class='far fa-edit'></i>".html_safe, edit_activity_path(activity), class: "edit-btn"  %>
              <%= link_to "<i class='far fa-trash-alt'></i>".html_safe, activity_path(activity), method: :delete, class: 'btn delete-btn' %>
            </div>
          </div>
        </div>
      </div>
      <% end %>



  </div>

</div>

app/views/users/edit.html.erb
<div class="all-container">
  <%= link_to "Back to profile", user_path(current_user) %>
  <%= simple_form_for current_user do |f| %>
  <%= f.input :username %>
  <%= f.input :first_name %>
  <%= f.input :second_name %>
  <%= f.label :nationality %>
  <%= f.country_select :nationality, class: "country-select"%>
  <%= f.input :bio %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit class: "btn btn-warning w-100"%>
  <% end %>


</div>

app/views/users/reviews.html.erb
<div class="all-container">
  <%= link_to "Back to profile", user_path(current_user), class: "return-btn" %>

  <% current_user.reviews.each do |review| %>
    <div class="card-product">

      <%= cl_image_tag review.activity.photo, alt: "alttext" %>
      <div class="card-product-infos">
        <% if review  %>
        <h2><%= review.activity.name %></h2>
          <div class="review-star">
            <% review.rating.times do  %>
              <i class="fas fa-star"></i>
            <% end %>
            <% (5 - review.rating).times do %>
              <i class="far fa-star"></i>
            <% end %>
          </div>
        <% else %>
          <% 5.times do %>
            <div class="review-
            star">
              <i class="far fa-star"></i>
            </div>
          <% end %>
        <% end %>
        <!-- <br> -->
        <div id='orange-btns'>
        <%= link_to "<i class='far fa-trash-alt'></i>".html_safe, activity_review_path(review.activity_id, review.id), method: :delete, class: 'btn delete-btn' %>
        <button type="button" class="btn edit-btn" data-toggle="modal" data-target="#exampleModal-<%= review.id %>">
          <i class="far fa-edit"></i>
        </button>
        </div>
      </div>

    </div>

    <div class="modal fade" id="exampleModal-<%= review.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Edit my review</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <%= simple_form_for [review.activity, review] do |f| %>
            <div class="modal-body">
              <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="close-review-btn" data-dismiss="modal">Close</button>
              <%= f.submit 'Save' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <br>
</div>

app/views/users/show.html.erb
<div class="cover-container">
</div>
<div class="all-container ">
  <div class="main-container">
    <div class="user-container">
      <div class="photo-container-big">
        <%= cl_image_tag(@user.photo.url) %>
        <% if !@user.nationality.nil? %>
          <p id="country-flag"><%= @user.country_flag %></p>
        <% end %>


      </div>
      <div>
        <h4><%= @user.first_name %> <%= @user.second_name %></h2>
        <p>Username: <%= @user.username %></p>
      </div>
    </div>
    <div class="bio-container">
      <p><%= @user.bio %></p>
    </div>
  </div>
    <% if @user == current_user %>

      <%= link_to activities_user_path(current_user) do %>
        <div class="boxrow user-link">
          <p>Activities I've added</p>
          <i class="fas fa-chevron-right"></i>
        </div>
      <% end %>

      <%= link_to edit_user_path(current_user) do %>
        <div class="boxrow user-link">
          <p>Edit my profile</p>
          <i class="fas fa-chevron-right"></i>
        </div>
      <% end %>

      <%= link_to destroy_user_session_path, method: :delete do  %>
        <div class="boxrow user-link">
          <p>Log out</p>
          <i class="fas fa-chevron-right"></i>
        </div>
      <% end %>
    <% else %>

        <p> <%= @user.first_name %>'s trips: </p>
          <% @user.trips.each do |trip| %>
            <%= link_to trip_path(trip) do %>
              <div class="boxrow user-link">
                <div>
                  <p><%= trip.trip_name %> | <%= trip.duration %> days </p>
                  <p><%= trip.likes %> likes</p>
                </div>
                  <i class="fas fa-chevron-right ours"></i>
              </div>
            <% end %>
          <% end %>
    <% end %>
</div>