config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'pages#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :activities do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    member do
      post 'up-vote'
      post 'down-vote'
    end
  end
  resources :trips do
    member do
      post 'like'
    end
    resources :shortlisted_activities, only: [:show, :new, :create]
    member do
      get 'trip_map'
    end
  end
  resources :users do
    member do
      get 'reviews'
      get 'activities'
    end
  end
  resources :shortlisted_activities, only: [:create, :destroy]
end

app/models/shortlisted_activity.rb
class ShortlistedActivity < ApplicationRecord
  belongs_to :activity
  belongs_to :trip
  validates :trip, uniqueness: { scope: :activity }
end

app/controllers/shortlisted_activities_controller.rb
class ShortlistedActivitiesController < ApplicationController
  def show
    @shortlisted_activity = ShortlistedActivity.find(params[:id])
    @activity = Activity.find(@shortlisted_activity.activity_id)
    @trip = Trip.find(params[:trip_id])

    # @activity_map = Activity.geocoded
    # @activity_geocoded = @activity_map.find(params[:id])
    @markers =
    [
      {
        lat: @shortlisted_activity.activity.latitude,
        lng: @shortlisted_activity.activity.longitude
      }
    ]
    @review = Review.new
    authorize @activity
    @activitytrips = ShortlistedActivity.where("activity_id = ?", @activity.id)
  end

  def new
    @trip = Trip.find(params[:trip_id])
    @activity = Activity.new
    authorize @activity
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @activity = Activity.new(activity_params)
    if params[:index] == "0"
      @activity.tod = "Morning"
    elsif params[:index] == "1"
      @activity.tod = "Afternoon"
    elsif params[:index] == "2"
      @activity.tod = "Evening"
    end
    @activity.city = @trip.activities.first.city
    @activity.user = current_user
    @activity.save!
    @shortlisted_activity = ShortlistedActivity.new
    @shortlisted_activity.activity = @activity
    @shortlisted_activity.trip = @trip
    @shortlisted_activity.day = params[:day]

    if @shortlisted_activity.save!
      redirect_to trip_shortlisted_activity_path(@trip, @shortlisted_activity)
    else
      render :new
    end

    authorize @shortlisted_activity
  end

  def destroy
    @shortlisted_activity = ShortlistedActivity.find(params[:id])
    @shortlisted_activity.destroy
    redirect_back(fallback_location: root_path)
    authorize @shortlisted_activity
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :rating, :description, :city, :tod, :price, :user_id, :photo)
  end

  def shortlisted_activity_params
    params.require(:shortlisted_activity).permit(:day, :trip_id, :activity_id)
  end
end

app/views/shortlisted_activities/_review.html.erb
<div class="review-info <%= class_to_add %> <%= class_identifier %>">
  <div class="d-flex">
    <div class ="photo-container-small">
      <%= cl_image_tag(review.user.photo.url) %>
      <p class="review-user"><%= review.user.username %></p>
    </div>
  </div>
  <div class="reviewstar">
    <% review.rating.times do  %>
    <i class="fas fa-star"></i>
    <% end %>
    <% (5 - review.rating).times do %>
    <i class="far fa-star"></i>
    <% end %>
  </div>
</div>

app/views/shortlisted_activities/new.html.erb
<div class="trip-title d-flex justify-content-center flex-column new-activity-head">
  <h3 class="my-trip-title">Add Activity To Your Trip </h3>
</div>
<div class="all-container activity-new">
  <div>
    <% if policy(Activity).create? %>
      <%= simple_form_for [@trip, @activity], url: trip_shortlisted_activities_path(day: params[:day], index: params[:index]) do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price, placeholder: '$' %>
      <%= f.association :categories %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.button :submit, "Add this activity", class: "btn btn-warning w-100" %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/shortlisted_activities/show.html.erb
<div class="all-container" style="">
  <div class="link-trip">
    <%= link_to "Back to trip", trip_path(@trip), class: "btn btn-warning" %>
  </div>
  <div class="text-center header-show">
    <h2><%= @activity.name %></h2>
    <p>Recommended for: <%= @activity.tod %></p>
  </div>
  <div class="image-contain">
    <div class="image-show" style="background-image: url(<%= asset_path check_photo(@activity.photo) %>)">
    </div>
  </div>
  <div class="show-rating">
    <div class="show-bold">
      <% if @activity.reviews.empty? %>
        <% 5.times do %>
          <div class="star">
            <i class="far fa-star"></i>
          </div>
        <% end %>
      <% else %>
        <div class="star">
          <% @activity.averagerating.times do  %>
            <i class="fas fa-star"></i>
          <% end %>
          <% (5 - @activity.averagerating).times do %>
            <i class="far fa-star"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="show-bold">
      <p>$<%= @activity.price %></p>
    </div>
  </div>

  <div class="description">
    <p><%= @activity.description %></p>
  </div>

  <div>
    <h5>Who else has done this?</h5>
    <div class="othertrips">
      <% if @activity.reviews.blank? %>
        <p>No one else has included this in their trip yet!</p>
      <% else %>
      <% @activitytrips.each do |shortlistedactivity| %>
        <% trip = Trip.find(shortlistedactivity.trip_id) %>
        <% user = User.find(trip.user_id) %>
          <% if user != current_user %>
            <div class="otherusers">
              <div class="userinfo">
                <%= link_to user_path(user) do %>
                  <div class ="photo-container-small">
                    <%= cl_image_tag(user.photo.url) %>
                    <p class="review-user"><%= user.username %></p>
                  </div>
                <% end %>
              </div>
              <%= link_to trip_path(trip) do  %>
              <div class="tripinfo">
                <p><em> <%= trip.trip_name %> </em> </p>
                <div>
                  <%= trip.created_at.day %>/<%= trip.created_at.month %>/<%= trip.created_at.year %>
                </div>
              </div>
              <% end %>
            </div>
          <% end %>
      <% end %>
      <% end %>
    </div>
  </div>

  <div class="review-act">
    <h5>Ratings</h5>
    <button type="button" class="btn btn-warning review-btn" data-toggle="modal" data-target="#rate">
      Rate
    </button>
  </div>

  <div class="review-show" id="reviews">
    <% if @activity.reviews.blank?  %>
      <p>Be the first to rate this activity</p>
    <% else %>
    <% @activity.reviews.each_with_index do |review, index| %>
      <% if index > 3 %>
        <%= render "review", review: review, class_to_add: "hide", class_identifier: "to-hide"  %>
      <% else %>
        <%= render "review", review: review, class_to_add: "", class_identifier: "" %>
      <% end %>
    <% end %>
    <% end %>
    <div class="text-center">
      <% if @activity.reviews.count > 4 %>
        <button id="show-reviews" class="ratings-button">Show more ratings</button>
      <% end %>
    </div>
  </div>

  <h4>On the map</h4>
  <div
    id="map"
    style="width: 100%;
    height: 250px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  >
  </div>
</div>

<div class="modal modal-review fade" id="rate" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content modal-content-review">
      <div class="modal-header">
        <h5 class="modal-title modal-title-review" id="exampleModalLabel">Rate</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for([@activity, @review], remote: true, html: { class: "review_form" }) do |f| %>
          <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", class: "text-center" %>
          <%= f.button :submit, class: "hidden" %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>