config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'pages#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :activities do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    member do
      post 'up-vote'
      post 'down-vote'
    end
  end
  resources :trips do
    member do
      post 'like'
    end
    resources :shortlisted_activities, only: [:show, :new, :create]
    member do
      get 'trip_map'
    end
  end
  resources :users do
    member do
      get 'reviews'
      get 'activities'
    end
  end
  resources :shortlisted_activities, only: [:create, :destroy]
end

app/models/activity.rb
class Activity < ApplicationRecord
  geocoded_by :name
  after_validation :geocode, if: :will_save_change_to_name?
  include PgSearch::Model
  pg_search_scope :search_by_city,
    against: [:city],
    using: {
      tsearch: { prefix: true }
    }

  TOD = ["Morning", "Afternoon", "Evening"]

  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :activity_categories, dependent: :destroy
  has_many :categories, through: :activity_categories, dependent: :destroy
  has_many :shortlisted_activities, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :city, presence: true
  validates :tod, presence: true, inclusion: { in: TOD }
  validates :price, presence: true
  validates :photo, presence: true
  mount_uploader :photo, PhotoUploader

  before_validation :add_city_to_name

  def add_city_to_name
    self.name = "#{self.name}, #{self.city}"
  end

  def averagerating
    thisactivity = Activity.find(self.id)
    totalratings = []
    allreviews = thisactivity.reviews
    allreviews.each do |review|
      totalratings.push(review.rating.to_i)
    end
    avg = (totalratings.sum / allreviews.length)
    return avg
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  skip_after_action :verify_policy_scoped, only: [:index]

  def index
    if params[:cardIds].nil? && session[:trips_params].present?
      params[:cardIds] = session[:trips_params]['cardIds']
    end
    if params[:days].nil? && session[:trips_params].present?
      params[:days] = session[:trips_params]['days']
    end
    if params[:place].present?
      place = params[:place].split.first
      @activities = Activity.near(place, 20)

    elsif
      params.dig(:filter, :place).present?
      filter = params[:filter]
      place = filter[:place].split.first
      @activities = Activity.near(place, 20)
    else
      @activities = policy_scope(Activity)
    end

    if params.dig(:filter, :categories).present?
      filter = params[:filter]
      @activities = @activities.joins(:categories).where(categories: { id: filter[:categories].reject(&:empty?).map(&:to_i) })
      @activities = @activities.uniq
    end

    if params[:cardIds]
      activity_ids = params[:cardIds].split(',').uniq.map(&:to_i)
      @activities = @activities.reject { |activity| activity_ids.include?(activity.id) }
    end
  end

  def show
    @activity = Activity.find(params[:id])
    if @activity.geocoded?
      @markers = [
        {
          lat: @activity.latitude,
          lng: @activity.longitude
        }
      ]
    end
    authorize @activity
    @place = @activity.city
    @activitytrips = ShortlistedActivity.where("activity_id = ?", @activity.id)
  end

  def edit
    authorize @activity
  end

  def new
    @activity = Activity.new
    authorize @activity
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    if @activity.save
      redirect_to activities_user_path(@activity.user)
    else
      render :new
    end

    authorize @activity
  end

  def update
    authorize @activity
    @activity.update(activity_params)
    redirect_to activities_user_path(@activity.user)
  end

  def destroy
    @activity.destroy
    redirect_back(fallback_location: root_path)
    authorize @activity
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:name, :rating, :description, :city, :tod, :price, :user_id, :photo)
  end
end

app/views/activities/_activity.html.erb
  <div class="activity-container">
    <%= link_to activity_path(activity) + '?days=' + (params[:days] || ''), class:'activity-show-link' do %> <!-- is this sending the cardIds? -->
      <div class="activity-photo"><%= cl_image_tag activity.photo, quality: :auto %>
    <% end %>
      <div class="activity-name">
        <h4><%= activity.name %></h4>
      </div>
    </div>
    <div class="activity-icons d-flex">
      <% activity.categories.each do |category| %>
          <div class="mr-2">
            <i class="<%= category.icon %> activity-card-icon"></i>
          </div>
      <% end %>
    </div>
    <div class="activity-rating">
      <% if activity.reviews.empty? %>
        <% 5.times do %>
          <div class="star">
            <i class="far fa-star"></i>
          </div>
        <% end %>
      <% else %>
          <% activity.averagerating.times do  %>
            <div class="star">
              <i class="fas fa-star"></i>
            </div>
          <% end %>
          <% (5 - activity.averagerating).times do %>
            <div class="star">
              <i class="far fa-star"></i>
            </div>
          <% end %>
      <% end %>
    </div>
  </div>

app/views/activities/_filter.html.erb
<div class="modal" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="filterModalLabel" aria-hidden="true">
  <div class="" role="document">

    <div class="modal-content">


      <%= simple_form_for :filter, url: activities_path, method: :get do |f| %>
        <%= f.input :place, as: :hidden, input_html: { value: params[:place] } %>
        <%= f.input :days, as: :hidden, input_html: { value: params[:days] } %>

        <div class="modal-body">
          <fieldset class="icon-box">
            <input type="hidden" name="filter[categories][]" value="">
                <div class="category-choices">
                  <% Category.all.each do |category| %>
                    <div class="col-4 each-icon p-10">
                        <input type="checkbox" class="d-none" value="<%= category.id %>" name="filter[categories][]" id="filter_categories_<%= category.id %>">
                        <label class="each-icon collection_check_boxes category-choice" for="filter_categories_<%= category.id %>"><%= category.name %>
                          <i class="<%= category.icon %>" for="filter_categories_<%= category.id %>"></i>
                        </label>
                    </div>
                  <% end %>
                </div>
          </fieldset>
        </div>

        <div class="modal-footer">
          <%= f.button :submit  %>
        </div>
      <% end %>

    </div>

  </div>
</div>
<%= content_for(:after_js) do %>
  <%= javascript_pack_tag 'components/radio_buttons' %>
<% end %>

app/views/activities/edit.html.erb
<div class="all-container">
  <div class="form-inputs">
    <%= simple_form_for(@activity) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :city %>
    <%= f.input :tod, collection: Activity::TOD %>
    <%= f.input :price, placeholder: '$' %>
    <%= f.association :categories %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.button :submit, "Edit this activity", class: "btn btn-warning w-100" %>
    <% end %>
  </div>
</div>

app/views/activities/index.html.erb
<div class="all-container d-flex flex-column" id="activitycontainer">

  <% if params[:place].present? %>
    <% place = params[:place] %>
    <% duration = params[:days] %>
  <% elsif params.dig(:filter, :place).present? %>
    <% place = params[:filter][:place] %>
    <% duration = params[:filter][:days] %>
  <% end %>

  <% if place && Activity.search_by_city(place.split.first) == [] %>
      <p>Sorry we don't have any activities in that city, search again!</p>

  <% elsif @activities.length == 0 %>

    <div class="noactivities">
      <p>Sorry, there are no activities for <%= place %> in those categories. Try another category!</p>
    </div>

  <% else %>
    <% if !params.dig(:filter, :categories).present? %>
      <div>
        <button class="iphone-fix" data-toggle="modal" data-target="#filterModal">Filter activities by category</button>
      </div>
    <% elsif params.dig(:filter, :categories).present? %>
      <p class="text">You selected: </p>
        <div class="categoriesfiltered">
          <% categories = params[:filter][:categories] %>
          <% categories.each do |category| %>
            <% if category.to_i > 0 %>
              <% cat = Category.find(category)%>
              <p class="cat"><%= cat.name %></p>
              <% end %>
            <% end %>
        </div>
      <p class="" data-toggle="modal" data-target="#filterModal">Edit filters</p>
    <% end %>

    <div id="viewport">

      <ul class="stack" id="activity-list">
        <% @activities.each do |activity| %>
          <li id="activity_<%= activity.id %>" data-id="<%= activity.id %>">
            <%= render 'activity', activity: activity %>
          </li>
          <div class="endoflist">
            <p >That's all the activities </p>
            <p> for <%= activity.city %>, time to </p>
              <p> plan your trip!</p>
          </div>
        <% end %>
      </ul>

      <%= content_for(:after_js) do %>
        <%= javascript_pack_tag 'components/swing' %>
      <% end %>
    </div>

    <div class="thum-btns">
      <p class="choicebutton n" id="no">Nope!</p>
      <p class="choicebutton y" id="yes">Hell yea!</p>
    </div>
    <div>
      <h4 class="trip-btn btn w-100"><%= link_to "Lets go to #{@activities.first.city}!", trips_path(days: duration, cardIds: params[:cardIds]), method: :post, id:'plan_trip_link', remote: false %>
        </h4>
    </div>

    <%= render 'activities/filter' %>
  <% end %>

</div>

<script>
  buttonOne = document.getElementById('yes')
  buttonOne.addEventListener('click', () => {
    console.log('hi')
    buttonOne.style.animation = 'pulse 1s ease'
    setTimeout(() => {
    buttonOne.style.animation = ''
    }, 1000)
  })

  buttonTwo = document.getElementById('no')
  buttonTwo.addEventListener('click', () => {
    console.log('hi')
    buttonTwo.style.animation = 'pulse 1s ease'
    setTimeout(() => {
    buttonTwo.style.animation = ''
    }, 1000)
  })
</script>

app/views/activities/new.html.erb
<div class="trip-title d-flex justify-content-center flex-column new-activity-head">
  <h4 class="my-trip-title">Add Activity </h4>
</div>
<div class="all-container activity-new">
  <div>
    <% if policy(Activity).create? %>
      <%= simple_form_for @activity do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :city %>
      <%= f.input :tod, label: 'Suggested time of day', collection: ["Morning", "Afternoon", "Evening"]  %>
      <%= f.input :price, placeholder: '$' %>
      <%= f.association :categories %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.button :submit, "Add this activity", class: "btn btn-warning w-100" %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/activities/show.html.erb
<div class="all-container container-padding">
  <div class="text-center header-show">
    <h2><%= @activity.name %></h1>
      <p>Recommended for: <%= @activity.tod %></p>
  </div>
  <div class="image-contain">
    <div class="image-show" style="background-image: url(<%= asset_path check_photo(@activity.photo) %>)">
    </div>
  </div>
  <div class="show-rating">
    <div class="show-bold">
      <% if @activity.reviews.empty? %>
        <% 5.times do %>
          <div class="star">
            <i class="far fa-star"></i>
          </div>
        <% end %>
      <% else %>
        <div class="star">
          <% @activity.averagerating.times do  %>
            <i class="fas fa-star"></i>
          <% end %>
          <% (5 - @activity.averagerating).times do %>
            <i class="far fa-star"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="show-bold">
      <p>$<%= @activity.price %></p>
    </div>
  </div>

  <div class="description">
    <p><%= @activity.description %></p>
  </div>
  <div>
    <h5>Who else has done this?</h5>
    <div class="othertrips">
      <% if @activity.reviews.blank? %>
        <p>No one else has included this in their trip yet!</p>
      <% else %>
      <% @activitytrips.each do |shortlistedactivity| %>
        <% trip = Trip.find(shortlistedactivity.trip_id) %>
        <% user = User.find(trip.user_id) %>
          <% if user != current_user %>
            <div class="otherusers">
              <div class="userinfo">
                <%= link_to user_path(user) do %>
                  <div class ="photo-container-small">
                    <%= cl_image_tag(user.photo.url) %>
                    <p class="review-user"><%= user.username %></p>
                  </div>
                <% end %>
              </div>
              <%= link_to trip_path(trip) do  %>
              <div class="tripinfo">
                <p><em> <%= trip.trip_name %> </em> </p>
                <div>
                  <%= trip.created_at.day %>/<%= trip.created_at.month %>/<%= trip.created_at.year %>
                </div>
              </div>
              <% end %>
            </div>
          <% end %>
      <% end %>
      <% end %>
    </div>
  </div>
  <div>
    <h5>Activity ratings</h5>
  </div>
  <div class="review-show">
    <% if @activity.reviews.blank? %>
      <p>There are no ratings for this trip yet</p>
    <% else %>
    <% @activity.reviews.each_with_index do |review, index| %>
      <% if index > 3 %>
        <%= render "./shortlisted_activities/review", review: review, class_to_add: "hide", class_identifier: "to-hide"  %>
      <% else %>
        <%= render "./shortlisted_activities/review", review: review, class_to_add: "", class_identifier: "" %>
      <% end %>
      <% end %>
    <% end %>
  <div class="text-center">
    <% if @activity.reviews.count > 4 %>
      <button class="ratings-button" id="show-reviews">Show more ratings</button>
    <% end %>
  </div>
  </div>
  <h5>On the map</h5>
  <div
    id="map"
    style="width: 100%;
    height: 250px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  >
  </div>

   <div class="thum-btns">
    <%= link_to activities_path(cardIds: params[:cardIds], days: params[:days], place: @place) do %>
      <p class="choicebutton n" id="no">Nope!</p>
    <% end %>
    <% card_ids = params[:cardIds].present? ? params[:cardIds] << ",#{@activity.id}" : @activity.id %>
    <%= link_to activities_path(cardIds: card_ids, days: params[:days], place: @place) do %>
      <p class="choicebutton y" id="yes">Hell yea!</p>
    <% end %>
    </div>
</div>

<script>
  buttonOne = document.getElementById('yes')
  buttonOne.addEventListener('click', () => {
    console.log('hi')
    buttonOne.style.animation = 'pulse 1s ease'
    setTimeout(() => {
    buttonOne.style.animation = ''
    }, 1000)
  })

  buttonTwo = document.getElementById('no')
  buttonTwo.addEventListener('click', () => {
    console.log('hi')
    buttonTwo.style.animation = 'pulse 1s ease'
    setTimeout(() => {
    buttonTwo.style.animation = ''
    }, 1000)
  })
</script>